spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/library_db
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: 9090