spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: 8080
microservice:
  librarian:
    ulr: http://localhost:8081/
  reader:
    ulr: http://localhost:8082/